server:
  port: 7001
  address: 192.168.1.8
spring:
  application:
      name: api-gateway
  cloud:
    gateway:
      routes: # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: auth_route # 当前路由的标识, 要求唯一
          uri: lb://service-auth # 请求要转发到的地址,lb是负载均衡
          order: 1 # 路由的优先级,数字越小级别越高
          predicates: # 断言(就是路由转发要满足的条件)
            - Path=/douyin/user/**  # 当请求路径满足Path指定的规则时,才进行路由转发
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=2 # 转发之前去掉2层路径 即去掉/douyin/user 真实访问地址为localhost:80/login

        - id: video_route
          uri: lb://service-video
          order: 2 # 路由的优先级,数字越小级别越高
          predicates:
             - Path=/douyin/publish/**

          filters:

        - id: video_route2
          uri: lb://service-video
          order: 2
          predicates:
            - Path=/douyin/feed/**



        - id: comment_route
          uri: lb://service-comment
          order: 3
          predicates:
              - Path=/douyin/comment/**
          filters:


      discovery:
        locator:
          enabled: true #让geteway从nacos获取服务信息
    nacos:
      discovery:
        server-addr: localhost:8848
