server:
  port: 8060

spring:
  application:
    name: service-comment


  datasource:
    username: root
    password: ran123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/douyin?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.douyin.entity

  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true


