server:
  port: 8090
  address: 192.168.1.11


spring:
  application:
    name: service-video


  datasource:
    username: root
    password: ran123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/douyin?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.douyin.entity

  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true


#    七牛云配置
oos:
  qiniu:
    domain:  rf7op4z1g.hn-bkt.clouddn.com # 访问域名(默认使用七牛云测试域名)
    accessKey: k49Y9sWMcyOuUVfGhtl3OcyJ87YdvNGrHPhNICv4 # 公钥
    secretKey: G2F8A2GQQyEB1uj2vZHpeo_ht8aMgmIx0P1RP9E7 # 私钥
    bucketName: douyinpicture  #存储空间名称