server:
  port: 80

spring:
  application:
    name: service-auth

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/douyin?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.douyin.entity

  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true